### ISSUE TITLE
Connected to a bluetooth sound system 

### ISSUE THREAD

**Issue by Nver464** [ryanheise/just_audio#1048]
**Is your feature request related to a problem? Please describe.**
If you are connected to a bluetooth sound system, and you play it "takes over" the sound.
If you are not connected, you can have two audio media playing.

**Describe the solution you'd like**
I'm using it to sound alerts in the app, so I need to be able to play with two audio sources, for example having a music app playing, and to be able to sound my alerts.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanheise** [comment]
I'm sorry I don't understand. The "Solution" you described doesn't sound like a solution, it sounds like the problem. And the "problem" you describe sounds sort of like a solution except it's a bit difficult to understand. And you haven't described any alternatives that you've considered.

**Comment by Nver464** [comment]
I am sorry, I mistook

As a solution I can't think of anything, something that caught my attention is that it only happens when it is with Bluetooth.
I reformulate the problem:
In the app, I have an alert that sounds after making a query, and I can have music with another app, both can be working simultaneously without problem, both sound sources; I keep listening to music and the alert sounds.
I just detected that when I make a query for the first time, with music from another app playing, the music pauses briefly, then continues without interruptions, both apps emitting sound.

Otherwise, when the mobile device is connected with a Bluetooth speaker system, I make the query while the music is playing from another app, it cancels the music from the other app.

**Comment by ryanheise** [comment]
I'm sorry, I still don't understand what you meant by "take over", and now you've added more things I don't understand, such as "making a query". Am I supposed to know what that means? Because there is no notion of queries in just_audio.

I would suggest that you research the native APIs that do what you're trying to do, and then edit your feature request to describe which APIs you would like me to implement in this plugin, assuming it is appropriate for this plugin.

**Comment by Nver464** [comment]
Resultado de traducción
I run queries on my platform, and I use just_audio to have alerts.

```
void playAlert(
  bool isActive,
) {
  String audioasset;
  if (isActive)
    audioasset = "assets/audio/beep.mp3";
  else
    audioasset = "assets/audio/stop.mp3";

  AudioPlayer _player = AudioPlayer();
  if (kIsWeb) {
    _player.setAudioSource(AudioSource.uri(Uri.parse(audioasset)));
  } else {
    _player.setAudioSource(AudioSource.asset(audioasset));
  }
  _player.play();
}
```

**Comment by ryanheise** [comment]
I'm sorry, I don't understand. Please try a different translator, e.g. deepL.

**Comment by Nver464** [comment]
How difficult not to speak the same language, sorry; tell me if it is already understood.
In the app, I have an alert that is triggered with just_audio after making a query of my data from a client, plus I am playing music with another app (spotify, youtube music,etc), both can be running simultaneously without problem, both sound sources; I keep listening to music and keep making queries and sounding the alerts results of my queries.
I just detected that when I query my database for the first time, with music from another app playing, the music from the other app pauses briefly, then continues uninterrupted, both apps playing sound, music and alerts with just_audio.

Here's the problem, when the mobile device is connected to a Bluetooth speaker system, I query my database while another app's music is playing, when the just_audio alert plays, the other app's music is paused.

**Comment by ryanheise** [comment]
If that's what you mean by "query", you're making this feature request too complicated. I don't need to know about those details. Although I'm still not 100% clear on exactly what the feature request is, it is starting to sound like something that is already explained in the README under the section "Configuring the audio session". I realise there is a language barrier, but please use a translator to read the README. This sounds like it is related to the audio session. Also, please read the documentation for the `AudioPlayer` constructor, since it provides the `handleAudioSessionActivation`.

**Comment by Nver464** [comment]
thank you
