### ISSUE TITLE
diffrence between AudioPlaybackState and AudioPlayBackEvent

### ISSUE THREAD

**Issue by mohammadne** [ryanheise/just_audio#110]
Hi @ryanheise 

What is diffrence between ```AudioPlaybackState``` and ```AudioPlayBackEvent``` ?
I mean that I can't understand your purpose of having both of them instead of only one state ?
because one of ```AudioPlayBackEvent``` property is ```AudioPlaybackState``` ?

also can I know that is it possible to make ```_playbackEventSubject``` not a private field ?
also it seems ```JustAudio``` becomes a very rich player but the only property is missing I guess is :
```
Stream<Duration> get volumeStream
```

Thanks

**Comment by ryanheise** [comment]
I don't plan to add more documentation on this because I am planning to change the state model soon. After that happens, I will update the documentation.

Note that `AudioPlaybackEvent` encapsulates data sent over the Flutter event channel. The word "event" is used to describe something happening at a particular moment in time. Every time something happens regarding the player on the platform side, it broadcasts an event to the Flutter side. All sorts of data is encapsulated in the event including the playback state.

The `AudioPlaybackState` is a state in the sense of a finite state machine. I think I'm using standard terminology here.

`_playbackEventSubject` is private because its purpose is to push events coming from the platform side, described in the first paragraph above. Making it private is good encapsulation.

If you'd like an additional property, please make a feature request following the template provided.

**Comment by ryanheise** [comment]
I'm closing this now that the new state model has been introduced and documented.
