### ISSUE TITLE
`PlayerException` Docs Missing Error Code Details

### ISSUE THREAD

**Issue by dickermoshe** [ryanheise/just_audio#1103]
**To which pages does your suggestion apply?**

- [PlayerException](https://pub.dev/documentation/just_audio/latest/just_audio/PlayerException-class.html)

**Quote the sentences(s) from the documentation to be improved (if any)**

> On iOS and macOS, maps to NSError.code. On Android, maps to ExoPlaybackException.type. On Web, maps to MediaError.code.

**Describe your suggestion**

Link to where this error code info is, I have searched for a while and cant find the apple docs for these error codes

**Comment by ryanheise** [comment]
To be honest, Apple's error code documentation is all over the place because there are different error domains with their own set of codes, and there is no document that tells you exactly which subset of errors is possible for a given API call. But if you receive an error, you can look it up by searching for that specific error. One thing that could help in the future is if the `PlayerException` included the error domain since that could help you to locate which specific list of error codes to look at (but again, searching directly for the error you encountered might be faster).

**Comment by ryanheise** [comment]
FYI, here is one domain that shows up a lot:

https://developer.apple.com/documentation/foundation/nsurlerrordomain?language=objc

**Comment by dickermoshe** [comment]
Maybe apple just has a bad layout, but I can't find a list of actual error codes/numbers.

**Comment by ryanheise** [comment]
That's correct, each error is defined as a constant, and while you can find various lists of these error symbols, you have to click on each one to view the page for that symbol which tells you the error code. If you want a list of all error codes, perhaps what you can do is find the Apple header files which may include the symbols and the numeric codes.

**Comment by ryanheise** [comment]
Here's the header file containing the error codes for the domain I mentioned above:

https://github.com/xybp888/iOS-SDKs/blob/master/iPhoneOS13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h

**Comment by dickermoshe** [comment]
Thanks. Thats perfect!
