### ISSUE TITLE
Because just_audio >=0.2.0 depends on path ^1.7.0 and every version of flutter_test from sdk depends on path 1.6.4, just_audio >=0.2.0 is incompatible with flutter_test from sdk.

### ISSUE THREAD

**Issue by azizk-araneux** [ryanheise/just_audio#111]
[FLUTTER_APP] flutter pub get
Running "flutter pub get" in FLUTTER_APP...                      
Because just_audio >=0.2.0 depends on path ^1.7.0 and every version of flutter_test from sdk depends on path 1.6.4, just_audio >=0.2.0 is incompatible with flutter_test from sdk.

So, because FLUTTER_APP depends on both just_audio ^0.2.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because FLUTTER_APP depends on both just_audio ^0.2.0 and flutter_test any from sdk, version solving failed.)
exit code 1

**Comment by ryanheise** [comment]
Hi @azizk-araneux please read and follow the instructions carefully when you post a new issue. I will reopen once you have edited your post to do so.

**Comment by naguchennai** [comment]
Because every version of flutter_test from sdk depends on path 1.6.4 and just_audio >=0.2.0 depends on path ^1.7.0, flutter_test from sdk is incompatible with just_audio >=0.2.0.
So, because tamilradiomusic depends on both just_audio ^0.2.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because tamilradiomusic depends on both just_audio ^0.2.0 and flutter_test any from sdk, version solving failed.)

**Comment by ariefwijaya** [comment]
same issue, any solution for this one ?

**Comment by ryanheise** [comment]
> same issue, any solution for this one ?

One solution to this is to please read and follow the instructions carefully when you post a new issue (as I mentioned above). Thanks.

**Comment by ariefwijaya** [comment]
Found the solution, it's because just_audio plugin using path version that doesn't updated yet on flutter stable. Just override the path version in your pubspec.yml:
```
dependency_overrides:
  path: 1.7.0
```
