### ISSUE TITLE
How to run from static List<double> data type

### ISSUE THREAD

**Issue by hasnin24** [ryanheise/just_audio#1115]
**To which pages does your suggestion apply?**  

https://pub.dev/documentation/just_audio/latest/just_audio/AudioSource-class.html

- Direct URL 1
- Direct URL 2
- ...

**Quote the sentences(s) from the documentation to be improved (if any)**

No documentation on how to read from static list<double>

for example: 

[0.00005239215533947572, 0.0000014616052794735879, -0.00008511867054039612, -0.00006905655754962936, 0.000015688463463447988, -0.0000017326583474641666, -0.00006541159382322803, -0.000050078597269020975, 0.0001162810658570379]

> Insert here. (Skip if you are proposing an entirely new section.)

**Describe your suggestion**

the current methods support only from url, assest and file. any suggesting/way to run from a static list?? 

...

**Comment by ryanheise** [comment]
There can't be any documentation for that because it is a non-existent feature. That is, there is no feature where you can pass in a list of double (I assume representing raw samples) and get an audio source.

iOS and Android at least only support playing encoded audio (e.g. mp3, m4a, ...), and this library does not do any encoding, just decoding.

The closest you could get is an encoded format like WAV which encodes raw samples, but you need to include the WAV header before that, which I can't help you with how to do. So if you can convert your double list into WAV format, then you can pass that to just_audio and have it play it.

There are two ways you can pass the WAV data to just_audio. One is to just write all the data to a file and then pass that file Uri into a UriAudioSource. The other way is to do it all in memory by using a StreamAudioSource to return a stream of raw WAV bytes in memory. Either approach will work but of course first you need to encode your audio data into one of these formats that Android and iOS / ... know how to read.
