### ISSUE TITLE
Windows label

### ISSUE THREAD

**Issue by Majd-AL-Shalash** [ryanheise/just_audio#1132]
**To which pages does your suggestion apply?**

- https://pub.dev/packages/just_audio

**Quote the sentences(s) from the documentation to be improved (if any)**

>![image](https://github.com/ryanheise/just_audio/assets/55484490/7d57b015-a402-45d4-9ee9-7d713853b05d)

**Describe your suggestion**

While the package support windows, I think we shoud add windows label to package

**Comment by ryanheise** [comment]
Unfortunately, those labels don't indicate that the plugin supports windows, they indicate that the plugin either directly supports windows internally, or that the plugin explicitly endorses a particular windows implementation provided external to this plugin -- neither of which is the case in just_audio.

So it's not really a matter of documentation, it's a matter of making a different decision about whether I should endorse a particular windows implementation. Since I want to actually support multiple alternative implementations, it is unfortunately not possible for me to endorse one implementation (there are actually limitations in the endorsement mechanism that mean that if I were to endorse one option, users wouldn't be able to override that with an alternative.)

In any case, since this is not about documentation (and the actual documentation does explain how to setup on windows), I'll close this.
