### ISSUE TITLE
Unsupported URL when trying to play downloaded audio on iPhone simulator

### ISSUE THREAD

**Issue by BethshanDeveloper** [ryanheise/just_audio#115]
**Describe the bug**
When trying to play an mp3 file using `setUrl` I encounter the PlatformException `unsupported URL`. The URL is `/Users/{username}/Library/Developer/CoreSimulator/Devices/A520E7A3-0301-4F56-97E5-D39412EB4E53/data/Containers/Data/Application/34504AF2-2077-4645-9FD8-8BE249FECEAA/Documents/Download/Worship_podcast_episode_6.mp3`. I'm not sure whether this is an issue of trying to play audio on the simulator, or an issue with this specific file. The same code and file work perfectly on Android.

**Minimal reproduction project**
It would be very tricky to create a project as I'd have to write the code to download the file from my Firebase project then play it. Hopefully the above is sufficient detail to describe the problem.

**To Reproduce**

**Error messages**

```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: unsupported URL
```

**Expected behavior**
I expect the package to be able to play audio from this URL.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: iPhone SE simulator
 - OS: iOS 12.2
 - Running on MacOS 10.15.4

**Flutter SDK version**
```
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.4 19E287, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.46.0)
[✓] Connected device (2 available)
```

**Additional context**
N/A

**Comment by BethshanDeveloper** [comment]
Originally I was using the audio_players package, but I switched to just_audio when I started using audio_service. audio_players can open and play a url like this, so I don't think it's an issue with permissions accessing that folder in the simulator, I think it is actually the just_audio `setUrl` function.

**Comment by BethshanDeveloper** [comment]
Ok I've just stumbled on the answer - apparently in order to open a local file like this one I need to add `"file://" to the front of my url. I worked this out by looking at your code in `https://github.com/ryanheise/just_audio/blob/master/darwin/Classes/AudioPlayer.m` line 190 where you make this check to distinguish local files.

I'm getting my path using `'package:path_provider/path_provider.dart'` `getApplicationDocumentsDirectory` which I believe is the standard way to do this in Flutter, and it doesn't prefix the url with `'file://'`. I'm not sure what the best way to resolve this bug is - at the moment I'm manually adding that string as a prefix, but it doesn't feel like it should be the developers responsibility to do that. If you feel that it is, I suggest this be clearly added to the documentation, either on the `setUrl` function in the code, or in the README.

**Comment by ryanheise** [comment]
You might be confusing the concept of a URL with a file path.

**Comment by BethshanDeveloper** [comment]
Ok, as a user it took me a while to work out what was wrong here and I didn't find it intuitive. I'm happy to raise another ticket for this under feature request as it's not really a bug, but which of these solutions would you prefer?

1. Update documentation (FAQ or setURL documentation string) to explain how to reference a local file
2. Rename setURL to setURI if it includes local files with the URI scheme file://
3. Extract local file reading into another function where you pass it the file path

**Comment by ryanheise** [comment]
> You might be confusing the concept of a URL with a file path.

What I meant by this comment is that there is a separate method for each of these, and there is also another one for assets:

`setUrl`
`setFilePath`
`setAsset`

Since the string you obtained from `path_provider` is a file path, not a URL, you should use `setFilePath` instead of `setUrl`. Your confusion is only from not recognising that a file path is not a URL, otherwise I suspect you might have found my API to appear more sensible than it first seemed.

file:// URLs *are* URLs, and so therefore can also be passed into `setUrl`. They are also URIs because URLs are a subset of URIs, but URIs are a much broader category that include things that are of no interest to this plugin.

There are many APIs that make use of the terms URL and file path, but in every case I have seen, the use of such a term does not warrant an explanation since the reader can look up the definition (but in these cases, I think they are also generally understood so most users will not need to look up the definition). One exception would be an API representing the definition of such a term. E.g. Dart has a `Uri` class, and within it, it would be appropriate to define what a Uri means. By the way, Dart's documentation for this class is even briefer than my own documentation, and more or less says "Go and read the RFC" :-)

>     2. Rename setURL to setURI if it includes local files with the URI scheme file://

I feel that "URI" is too broad. It is only URLs that I want to support.

>     3. Extract local file reading into another function where you pass it the file path

This already exists in `setFilePath`.

**Comment by ryanheise** [comment]
This API will change once #36 is implemented and so this question may resurface in the choice of naming URI vs URL.

But for now, I think the documentation is accurate on `setUrl`, `setFilePath` and `setAsset`. Are you OK if I close this now?

Note that Flutter uses the `Uri` class even for method parameters where only a URL would be appropriate. So you have examples such as `HttpClient.getUrl` which have `Url` in the name but take a `Uri` parameter because there is no `Url` data type in Dart. The reasoning is that the parameter should be a URL, but for convenience there is no need to invent a new parameter type called `Url`. `Uri` can be  used "as" a URL.

**Comment by BethshanDeveloper** [comment]
I think many people don't really appreciate the difference between a URI and a URL anyway to be honest, so I'm happy for you to close this, thanks!
