### ISSUE TITLE
[iOS 17] Can't play a sound when a call is active

### ISSUE THREAD

**Issue by phuchuynh81qn** [ryanheise/just_audio#1163]
[iOS 17] Can't play a sound when accepting call using callkit in ios 17, ios 15, 16 work fine.

**Comment by phuchuynh81qn** [comment]
@ryanheise Can you help me?

**Comment by wbbtech** [comment]
I have this same problem when trying to play streaming audio on iOS 17 physical devices, the audio cannot be heard.

```
Future<void> _getUrlRadio() async {
    try {
     // https://27323.live.streamtheworld.com/CARACOL_RADIOAAC_SC?csegid=2000
      final res = await _apiGet.getUrlRadio();
      Uri? uri = Uri.tryParse(res);
      if (uri == null || res.isEmpty) throw '';

      await _player.setAudioSource(AudioSource.uri(uri));

      print(".- _getUrlRadio: $uri");
      return _player.play();
    } catch (_) {
      print(".- _getUrlRadio Err: $_");
    }
  }
```

**Comment by ryanheise** [comment]
> @ryanheise Can you help me?

Unfortunately not, because you have submitted an invalid bug report where you ignored my instructions and deleted all of the required sections.

In the first section, you need to justify why this is indeed a bug and not the proper behaviour of iOS 17. In the second and third section, you need to provide a minimal reproduction project and instructions for me to run it.

**Comment by ryanheise** [comment]
Quick Google Search:

https://forums.developer.apple.com/forums/thread/738940
https://stackoverflow.com/questions/53976645/audio-not-working-when-incoming-call-is-answered-during-screen-is-locked-swift
...

I did not see that this is a just_audio bug. If you disagree, you need to fill in a proper bug report with all of the information I require.

**Comment by ryanheise** [comment]
Closing as no response.
