### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by KristijanZic** [ryanheise/just_audio#1164]
Is the Linux support coming? What would be an ETA for it?

**Comment by ryanheise** [comment]
![image](https://github.com/ryanheise/just_audio/assets/19899190/a3c22851-90b7-4eb1-bbd4-bce95f96d74c)

Just how many words into the README page did you make it before you gave up? Linux is available as a federated plugin implementation, so you could need nothing more than what is already available. The README contains all the instructions, just hit Ctrl+F "linux" if you don't want to read all of the README and you will instantly find the parts that mention Linux.

(Speaking of reading things, the first line of the instructions for submitting an issue says: "PLEASE READ CAREFULLY!" - I guess you also didn't make it that far before you deleted it. Might I suggest reading, as I don't have time to answer everyone's questions individually, that's why I have written the README, the docs and the issue submission instructions.)

**Comment by KristijanZic** [comment]
You're right. I feel beyond ashamed and I apologize, thank you 🙏
