### ISSUE TITLE
Feature: Composite Media Source

### ISSUE THREAD

**Issue by rohansohonee** [ryanheise/just_audio#14]
Have functionality for ``ConcatenatingMediaSource`` as in exoplayer where multiple media sources can be added.
> Concatenates multiple MediaSources. The list of MediaSources can be modified during playback. It is valid for the same MediaSource instance to be present more than once in the concatenation. Access to this class is thread-safe.

This means we can setUrl/setFilePath and form even a playlist. i.e loop through queue and add media sources using the ``ConcatenatingMediaSource`` option.

exoplayer sample has implemented the code this way:
``` java
 ConcatenatingMediaSource concatenatingMediaSource = new ConcatenatingMediaSource();
    for (Samples.Sample sample : SAMPLES) {
      MediaSource mediaSource = new ExtractorMediaSource.Factory(cacheDataSourceFactory)
          .createMediaSource(sample.uri);
      concatenatingMediaSource.addMediaSource(mediaSource);
    }
    player.prepare(concatenatingMediaSource);
    player.setPlayWhenReady(true);
```
``sample.uri`` is the url/filePath of the media/audio file.
``SAMPLES`` is the queue.

Hope I have been clear.

**Comment by ryanheise** [comment]
This feature would allow the player to reuse the same `AudioTrack` when achieving gapless playback, but at the same time, it would also prevent you from being able to implement cross fading yourself since the `setVolume` method could only control whatever is going into that one `AudioTrack`.

That means that either you'll need all of these features to be built into the plugin, or you'll just need the existing API to work better so that there's no audio popping and no illegal states. Since we want no popping anyway, I'll create a separate issue for that.

**Comment by rohansohonee** [comment]
@ryanheise 
Now this feature can be implemented into just_audio.
Changing Progressive Media Source to Concatenating Media Source, thus enabling gapless playback.

**Comment by ryanheise** [comment]
@rohansohonee Is this not needed anymore? I think it would be a good future direction to change the API to have a `setMediaSource` instead of individual methods like `setUrl`, `setAsset` and so on, and this would make it easier to consider things like a composite media source.

**Comment by rohansohonee** [comment]
I have just opened a new issue #36  and it mentions queue management aka composite media source. Hence I closed this one.
