### ISSUE TITLE
Apple Testflight rejection - Needs info.plist NSMicrophoneUsageDescription setting.

### ISSUE THREAD

**Issue by tnaseem** [ryanheise/just_audio#180]
**Is your feature request related to a problem? Please describe.**
Apple TestFlight rejected the app stating that there's a missing _NSMicrophoneUsageDescription_ setting in the Info.plist file.

Rejection email from Apple:

> **ITMS-90683: Missing Purpose String in Info.plist** - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a _NSMicrophoneUsageDescription_ key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Describe the solution you'd like**
I need help on how to get around this, without needing to update the plist file with the string, as I don't use any recording ability; Only playback.

**Describe alternatives you've considered**

**Additional context**

**Comment by ryanheise** [comment]
If your app is not using the microphone, you can safely add this key to Info.plist and the usage description will not be shown to the user, but Apple's automated code scanner will still ask for this key because it detects some code for audio options that "could" be used for this purpose, but isn't smart enough (yet) to detect that your app doesn't actually use it.

I'm looking into whether better solutions exist, but for now this should work. I will need to update the README for the time being with the above.

**Comment by tnaseem** [comment]
Many thanks for letting me know.

I just did that and it got through the automated test and approved. On running, no alert popped up either, as you mentioned. That's the only thing I was worried about, tbh.

Thanks for the quick reply and help!

**Comment by ryanheise** [comment]
Glad to know it's now working for you. I've now updated the README to reflect the above comments, and will leave this issue pinned to help others with the same question.

**Comment by zierka** [comment]
@ryanheise I looked into the code and it looks like we could get rid of this requirement of adding microphone usage description. 

It seems to me like the only code that could trigger this are `AVAudioSessionCategoryRecord` and `AVAudioSessionCategoryPlayAndRecord` ([here](https://github.com/ryanheise/just_audio/blob/122a90b4fbb1d160ccba1a926fcd43a2282a1cc8/darwin/Classes/JustAudioPlugin.m#L40)), however it looks like the "setIosCategory" functionality has been removed from the library ([audio_session](https://pub.dev/packages/audio_session) needs to be used for that as the README states), and it seems like there's no reference of calling the "setIosCategory" anymore, so I'm wondering if we could remove that whole code block?

**Comment by ryanheise** [comment]
Unfortunately that won't get rid of this requirement. `setIosCategory` (or something of the sort) is still required, it's just that it has been factored out into a separate library which is linked and therefore still included in your app.

Apple's new app checker is a bit unreasonable given the way the SDKs Apple is referring to work.

So what solutions would work?

1. I could split the audio_session library into two halves where the split is dictated by Apple's "current" delineation of normal/sensitive APIs. Then app developers could either add both dependencies to their pubspec.yaml if necessary or just one. This wouldn't be easy for the plugin maintainer or the plugin user. Since Apple keeps changing their static analyser, there's no guarantee that this approach would be future proof, and so the only future proof approach might be to create a separate plugin for each enum value (It's not really possible for just_audio or audio_session to assume which enum value any given app needs).

2. Maybe a more desirable option would be to use some sort of compiler flags or configuration options which affect which can control which parts of the Objective C code get linked into your app. I'm not sure if there is a way to do this with the current build system, I'll have to look into it.

For now, though, it is harmless to include a purpose string in Info.plist for an API included in a library which is unused.

**Comment by ggirotto** [comment]
What about using a strategy similar to [`permission_handler`](https://pub.dev/packages/permission_handler#setup) using macros in the `Podfile`?

**Comment by ryanheise** [comment]
@ggirotto This is actually already implemented in the latest version of just_audio, but I just haven't documented it yet. I will update the documentation in the next release.

In the meantime, you can find instructions in the README of the latest audio_session release:

https://pub.dev/packages/audio_session#ios-setup

**Comment by ggirotto** [comment]
Hey @ryanheise thanks for the update. To disable mic usage in `just_audio` the flag is the same? I mean the flag `AUDIO_SESSION_MICROPHONE`:

```
target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'AUDIO_SESSION_MICROPHONE=0'
      ]
    end
```

Or it is `JUST_AUDIO_MICROPHONE`?

**Comment by ryanheise** [comment]
The flag is the same.

**Comment by ryanheise** [comment]
The 0.8.1 release includes the updated README which documents how to pass this build-time option, so I'll close this issue.
