### ISSUE TITLE
HTTP Headers For Player

### ISSUE THREAD

**Issue by aljibbs** [ryanheise/just_audio#224]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have audios on a server that requires authentication headers to get the audios. Is there a way with this plugin to set headers for the player to play audios in such instances ?

**Describe alternatives you've considered**
Currently, I have taken down the auth to enable the player access the audios but being able to set headers as a feature of the player will be the best option.

**Additional context**

**Comment by ryanheise** [comment]
To be specific, can you tell me which API method or constructor call you are currently trying to pass the URL into, and exactly what parameter you are proposing to add to it that's not already there? As evidence that it's not already there, it will help if you can point me to the documentation page for the specific method/constructor you're proposing to change.

**Comment by aljibbs** [comment]
What I am trying to ask is this, is it possible to set request headers to the player, if yes how is it done if not, it'll be a great feature to have considering a scenario where an audio is behind a url that needs an authentication header.

**Comment by ryanheise** [comment]
I will close this feature request since it is a question rather than a feature request.

Note that this GitHub issues page is intended solely for contributing to the development of the plugin, and it is not for asking for help or general support. I have provided a link on the "New issue" page for people who are asking for help and you should probably follow that link instead.

There are two links. One is to Stack Overflow, and the other is to Gitter. You can format your question like this: "How can I set request headers with just_audio?" or "Is it possible to set request headers with just_audio?" (rather than asking the developer to go and add this feature without even having looked into whether the feature already exists). Note that even StackOverflow has a high bar for what constitutes a good question, and if you go in there asking a question without showing that you have already done some research (something which your feature request above also lacks), then people will generally not be motivated to help you there either.

Therefore, I would actually recommend you to do what I originally asked in my previous comment above and actually read the documentation for the specific method or constructor where you pass in the URL.
