### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses'.

### ISSUE THREAD

**Issue by slimyTextBox** [ryanheise/just_audio#227]
Build failed with exception when the package is included in the project: just_audio 0.5.5

I posted the bug on flutter page also
https://github.com/flutter/flutter/issues/69236

This exception is reported on the link below, I tried most solutions on that page to no av
https://github.com/flutter/flutter/issues/49938
Failed solutions:

1- deleting build folder

2-
flutter channel stable
flutter upgrade --force
flutter pub cache repair
cd <YOUR APP FOLDER>
flutter clean

3- Through android studio: File > Invalidate Caches/Restart...

**To Reproduce (i.e. user steps, not code)**
1. add just_audio 0.5.5 package to yaml
2. click debug/run
3. See error

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-26.0-android.jar (com.google.guava:guava:26.0-android) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VSCode

**Smartphone (please complete the following information):**
 - Device: samsung s8
 - OS: [android 9]

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1139], locale en-CA)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.50.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by ayyshim** [comment]
If you are still struggling with the issue try adding
`implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'`
inside dependencies in your `android>app>build.gradle`  file. It worked for me.

**Comment by ryanheise** [comment]
@ayyshim thanks for contributing, and yes hopefully it helps others. I'd like to suggest this in the README, but first I want to reproduce the issue for myself so I'll wait for someone to post a complete bug report with a reproduction project.

@slimyTextBox if you're still reading, it would be a valuable contribution to the plugin if you could submit that. Simply "(adding) just_audio 0.5.5 package to yaml" is not enough to reproduce it because the example already does that and doesn't exhibit the bug, the bug is only present with certain combinations of dependencies which you haven't included in your reproduction information.
