### ISSUE TITLE
I found that for Android system /storage/emulated/0/Android/data/com.example.recording/files/recorder_1605022820835.wav The audio file will have an error

### ISSUE THREAD

**Issue by Basums** [ryanheise/just_audio#241]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**

**Error messages**

```
If applicable, copy & paste error message here, within the triple quotes to preserve formatting.
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```
insert output of "flutter doctor" here
```

**Additional context**

**Comment by lexyfeito** [comment]
Any news on this? I am facing the same error.

**Comment by ryanheise** [comment]
This issue is missing all of the required sections, so I wasn't able to investigate it.

I'll close this, but please take a look at #158 which is similar and I was able to investigate that one.

If your issue is different, I would suggest opening a new issue (but don't forget to fill in the required sections.)

Thanks.

**Comment by ryanheise** [comment]
This issue is missing all of the required sections, so I wasn't able to investigate it.

I'll close this, but please take a look at #158 which is similar and it was able to be investigated.

If your issue is different, I would suggest opening a new issue (but don't forget to fill in the required sections.)

Thanks.
