### ISSUE TITLE
Remove range from ConcatenatingAudioSource errors out if you remove the last item

### ISSUE THREAD

**Issue by pschuegr** [ryanheise/just_audio#275]
**Which API doesn't behave as documented, and how does it misbehave?**
When attempting to remove the last item using `audioSource.removeRange` or `removeAt`, the method call fails with:

```
2021-01-06 15:15:42.620 example[14647:12591690] Error in handleMethodCall
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)
```

Understood that this is an untested API.

**Minimal reproduction project**
https://github.com/pschuegr/just_audio/commit/5d5397544d46df3d539e919246f30363db873a15

**To Reproduce (i.e. user steps, not code)**
- Play audio in the example
- Remove using the cancel button until you hit the error

**Error messages**

```

2021-01-06 15:15:42.620 example[14647:12591690] Error in handleMethodCall
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Error in handleMethodCall, null, null)

```

**Expected behavior**
Handles removing the last item gracefully.  FWIW, I was able to solve this for my use case by changing some lines in `enqueueFrom`:

```
-    if (_loopMode == loopAll) {
+    if (_loopMode == loopAll && [_order count] > 0) {
```

It doesn't fix this example :) so I think there might be more to the real fix but it's probably a lot of `if !empty` type stuff?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser: N/A

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)
```

**Additional context**
Bitten by the dartfmt again but the change is here for ref https://github.com/pschuegr/just_audio/commit/5d5397544d46df3d539e919246f30363db873a15#diff-e2829964f0b5d7e87a71bdac1cef2291c4ee173b10f8bb124b5f76c838afa270R113

**Comment by ryanheise** [comment]
Thanks for reporting this. Fortunately I've been able to postpone handling empty lists so far as it hasn't turned out to be a major use case, but with a concrete use case now, that definitely raises its priority.

Since I'm currently finishing of another feature, it may take me a couple of days to look at it, but if you need a workaround until then, you will probably need to disable deleting the last item in the UI, or allow deleting it and then secretly don't delete it. Hopefully I'll be able to offer an actual solution, though.

**Comment by pschuegr** [comment]
No problem at all, I've got a workaround that's working for me for the moment.  Thanks for your work on this and thanks for the comment on the firebase ticket, much appreciated.

**Comment by ryanheise** [comment]
Apologies it has taken more than a couple of days to get around to this one. I will hopefully be able to look into it soon.

**Comment by ryanheise** [comment]
FYI, I have fixed the error but I've stashed it temporarily until I fix the other issue I was working on. Hopefully I'll have it ready for testing some time today.

**Comment by ryanheise** [comment]
Hi @pschuegr this now should be fixed (hopefully) in the latest commit. Let me know if it works for you or if you notice any problems with it.

**Comment by pschuegr** [comment]
My original repro case no longer causes problems, I'll ping if I notice anything.  Thanks!

**Comment by ryanheise** [comment]
This fix is now released in 0.6.6. Thanks again for helping to report and test.

**Comment by semack** [comment]
0.7.1 crashes with preload: true
_player.setAudioSource(null);

I need to reset the audio source and receive zero Position and Duration streams in my app, in other words - reinitialize the player to a state like it was just created. 

I tried to do the workaround with WAV contains a zero-length PCM block, it works perfectly well on Android but crashed on iOS cuz its codec can not handle PCM with such lenght.

Any ideas are appreciated.

Thanks in advance.

**Comment by ryanheise** [comment]
0.7.1 is a null-safe release and is intended to be used with the null-safe analyzer. The type of the parameter is non-nullable which means you are not (with the right analyzer) allowed to pass in `null`. I guess that you were able to pass in `null` only because you haven't upgraded your app to null safety yet.

What you can do instead is create a `ConcatenatingAudioSource` with one item in it, and then instead of `setAudioSource(null)` you can just remove the item from the `ConcatenatingAudioSource` and call `player.stop()`. This should work now that the bug you are commenting on is fixed.
