### ISSUE TITLE
Pitch

### ISSUE THREAD

**Issue by nt4f04uNd** [ryanheise/just_audio#276]

**Comment by nt4f04uNd** [comment]
@ryanheise reopen this

**Comment by ryanheise** [comment]
@nt4f04uNd I have an issue template for a feature request. Please click on "New issue", and then click on the button next to "Feature request" and follow the instructions within the issue template.

I'm sorry the bot misidentified your issue as a bug. The bot is pretty limited, and fires if your issue doesn't follow the required template. If you follow my instructions above, it should go through OK. It is important to follow the instructions specifically for "Feature request" so that you can provide relevant information about your use case. Posting a single word title without filling in the template sections of the feature request will be rejected by the bot. Note also that there there is no native pitch shifting API on iOS. An Android-specific feature could be implemented in the short term if there is enough demand for it. On the iOS side it would require rewriting the entire plugin to move away from AVQueuePlayer and to something more low level. That is unfortunately not a short term project.

Thanks for understanding, and as mentioned please follow the instructions above to open a new issue as per the Feature request template.

**Comment by ryanheise** [comment]
@nt4f04uNd FYI I have opened a new issue for this feature #329 .
