### ISSUE TITLE
Pan stereo channels control for playing audio

### ISSUE THREAD

**Issue by ProgrammingLife** [ryanheise/just_audio#340]
**Is your feature request related to a problem? Please describe.**
I wanna mix my sounds playing simultaneously using pan stereo control to play first sound in the left ear (in a range of [0..1]) and some sound in the right ear. I wanna have dynamically controlled feature to change this on the fly (online).

**Describe the solution you'd like**
I don't know what flutter plugin can do so.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ryanheise** [comment]
Looks like there was some discussion on this here for ExoPlayer: https://github.com/google/ExoPlayer/issues/2659 (it is described as a niche feature so the app must implement it manually, although we can't take that approach with Flutter since audio processing over method channels won't be very efficient).

For iOS, it's a built-in feature of `AVAudioPlayer` although that's not the API just_audio is based on. Maybe this can be done after the iOS side is reimplemented based on AVAudioEngine.

**Comment by ryanheise** [comment]
This also appears to be a duplicate of #126 (would you agree to closing this issue in favour of that one?)

**Comment by ProgrammingLife** [comment]
@ryanheise, sure I'll close this issue.

So is the best way for getting this functionality is to use a server power for quick mixing my sounds (to use desired L/R channel volumes) and playing a stream with just_audio? What do you think?

**Comment by ryanheise** [comment]
I will copy and paste these comments over to #126
