### ISSUE TITLE
Is speed orthogonal to play pause?

### ISSUE THREAD

**Issue by yringler** [ryanheise/just_audio#438]
**To which pages does your suggestion apply?**

- https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer-class.html
- https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setSpeed.html

**Quote the sentences(s) from the documentation to be improved (if any)**

> Sets the playback speed of this player, where 1.0 is normal speed.

**Describe your suggestion**

When I first used just_audio, a long time ago. `pause` was equivalent to `setSpeed(0)`. Which meant that a naive implementation of a button to change speed would mean that changing speed would make the audio play. Giving user the ability to change speed while audio is paused required app developer to keep track of speed distinctly from just_audio.
An alternative way of doing this would be for just_audio to keep track of play back speed, distinctly from current play/pause state, just like volume isn't changed by play/pause state.

I don't know that I have a strong preference either way, but I think it should be documented.

(I'm getting into this discussion again as part of my work on my new one isolate just_audio_task, currently being worked on [here](https://github.com/yringler/inside-app/tree/85-audio-one/just_audio_handlers). I would be amiss if I didn't note that audio_service one_isolate is AWESOME and a dream to work with. Thank you!)

**Comment by ryanheise** [comment]
That's a good point because the behaviour actually used to be inconsistent between platforms. On Android they have always been orthogonal, while on iOS pause and setSpeed interfered because they were both implemented using the same mechanism. Since then, the iOS implementation has been changed to work the way Android works, but yes it should be documented.

There are other platform-specific differences with setSpeed which might be a bit difficult to fully document because I don't fully understand them myself. In particular, the valid range of speed values. Android supports very high speed multiples but it has to be positive. iOS supports negative speed values, but is limited on the upper end in ways that vary depending on the type of audio source. There is supposed to be an API for querying the capabilities of the audio source in iOS but it doesn't actually work according to its own documentation.

**Comment by ryanheise** [comment]
I wonder if it would be better to find a way to do it by documenting what each method does rather than what each method doesn't do.

I've updated the documentation of `play` as follows:

```dart
  /// Tells the player to play audio at the current [speed] and [volume] as soon
  /// as an audio source is loaded and ready to play.
...
  /// This method causes [playing] to become true, and it will remain true
  /// until [pause] or [stop] is called.
```

Thus, `play` is the only method that sets `playing` to `true`, while `setSpeed` and `setVolume` only set the `speed` and `volume` (but not `playing`).

Will this work?

I could perhaps also update the docs for `setSpeed` to say that it does not cause audio to start playing, although for consistency I would have to also document that `setVolume` doesn't do this (and maybe others).

**Comment by yringler** [comment]
> Will this work?

I think that's great!

> I could perhaps also update the docs for setSpeed to say that it does not cause audio to start playing, although for consistency I would have to also document that setVolume doesn't do this (and maybe others).

Or, to focus on what it does rather than what it doesn't do (which is a clearer way of writing) - Something like this?
```
/// Sets what the playback speed of this player will be when [playing] is true, where 1.0 is normal speed.
/// Note that values in excess of 1.0 may result in stalls if the 
/// playback speed is faster than the player is able to downloaded the audio. 
```

I don't think it's as relevant to volume, because people are used to (for example) muting a video for a second (and observing that playback doesn't stop), but setSpeed(0) will of course pause the playback. So there's an intuitive, suspected relationship between speed and play/pause which volume doesn't have.

**Comment by ryanheise** [comment]
Sounds good to me, I've now added something to that effect in 0.9.2:

```dart
/// Sets the playback speed to use when [playing] is `true`
```
