### ISSUE TITLE
set pitch not working on IOS

### ISSUE THREAD

**Issue by walikhan226** [ryanheise/just_audio#456]
Unhandled Exception: MissingPluginException(No implementation found for method setPitch on channel com.ryanheise.just_audio.methods.7450b310-272f-4dcb-a646-f4dd94d14d28)

**Comment by leidig54** [comment]
This is because the code is throwing a (caught) error whenever `Future<AudioPlayerPlatform> setPlatform()` is called on iOS.

```
 try {
          await platform.setPitch(SetPitchRequest(pitch: pitch));
        } catch (e) {
          // setPitch not supported on this platform.
        }

```

It is a bit of a disruption to the productivity flow - my app can run without any errors, caught or otherwise, except for this one.

Perhaps an `if (_isAndroid())` would be more appropriate?

**Comment by ryanheise** [comment]
Regarding the original issue, this is expected behaviour: `setPitch` is not supported on iOS, and not a bug. The feature hasn't been implemented on all platforms, but follow #329 for progress, and note the README for what features are supported on which platforms.

Regarding the try/catch, this is the correct way to test if a feature is supported _within the context of the plugin frontend_ because each method is defined to throw an exception if it is not supported on that platform, and the complete set of platforms is unsealed and so the complete set of platforms that support a feature is unknown by the plugin frontend. Thus, an app should do its own `if (isAndroid)` checks, because the app developer will have a sealed set of platforms being targeted, and will be able to code specifically for those platforms.

> This is because the code is throwing a (caught) error whenever `Future<AudioPlayerPlatform> setPlatform()` is called on iOS.

This code basically says: When activating the platform, restore any previous pitch that was set, except on platforms that don't actually support pitch shifting.

> It is a bit of a disruption to the productivity flow - my app can run without any errors, caught or otherwise, except for this one.

`setPitch` should not cause any errors unless you call it on a platform where pitch shifting is not supported, but an app can avoid doing that by checking the README for supported features per platform and adding conditional code to the app to make it work in whatever way it can be supported for each platform.

**Comment by leidig54** [comment]
Hi Ryan.

That you for the detailed reply. 

I think the issue is that `setPlatformActive() ` is called regardless of the platform (in the AudioPlayer constructor, and in most of the other key methods), and this contains a call to `setPitch()`. 

I am not calling setPitch() anywhere else in the code - it is being called whenever an instance of AudioPlayer is initialised - including on unsupported platforms.

**Comment by ryanheise** [comment]
> I am not calling setPitch() anywhere else in the code - it is being called whenever an instance of AudioPlayer is initialised - including on unsupported platforms.

It is intended that setPitch is called on all platforms, even unsupported platforms. For an unsupported platform, the platform will respond with "I don't support setPitch`, and then the plugin frontend will say "OK, I'll silently skip over this without error."

It is as intended, but I'm wondering, what problem, if any, could this cause if the error is handled internally as intended?

**Comment by leidig54** [comment]
Perhaps this is an IDE specific issue. 

I run my app on VSCode with a breakpoint set for all exceptions - hence it stops my app running every time I use AudioPlayer and I have to manually clickthrough the stack trace to continue running. Not a huge problem though, certainly nothing in production, and I can change the settings to respond to uncaught exceptions only.

**Comment by ryanheise** [comment]
I can see how that would be frustrating. It seems there is a flutter issue in which Dan Tup suggests in one comment selecting "Uncaught exceptions" rather than "All exceptions":

https://github.com/flutter/flutter/issues/33427#issuecomment-499055380

**Comment by walikhan226** [comment]
it works find with android but it throws exception on ios
