### ISSUE TITLE
Incorporate recording to make just_audio a single all-purpose audio plugin

### ISSUE THREAD

**Issue by alexda12** [ryanheise/just_audio#523]
**Is your feature request related to a problem? Please describe.**
No - this is just a feature request to introduce a new plugin called  JAR-> 'Just_Audio_Recorder'

**Describe the solution you'd like**
Just_audio is a great if not the best audio plugin for Flutter. The architecture allows for additional audio plugins to be seamlessly plugged in such as just_audio_background, audio_service, audio_session etc.

However - there is one further audio requirement that would make just_audio perfect - the ability to efficiently record audio supporting a wide variety of codecs.

**Describe alternatives you've considered**
There are not too many audio recording plugins available. The main plugin that is constantly evolving is Flutter_sound & Flutter_sound_lite.

**Additional context**
The current architecture of just_audio and its sibling plugins is very much reactive which aids in its simplicity and popularity. By having the ability to record audio built into a new plugin-> "just_audio_recorder" would also alleviate the many issues experienced when trying to mix and match different flutter audio plugins from other plugin developers. 

Just_audio has a solid developer base who appreciates just_audio and sibling plugins not just because of the wealth of unique features that all of these plugins offer but also because of the stability, architecture, ease of use, performance and more importantly - the constant ongoing support and further R&D of these plugins - bringing the same passion of development to the proposed just_audio_recorder plugin would be awesome.

**Comment by ryanheise** [comment]
It is indeed the philosophy of just_audio to just focus on one thing and let other plugins handle separate responsibilities. At the same time, I don't mean to imply that I would personally write those other plugins. I would hope for an ecosystem where all audio plugin developers agree to create plugins in such a way that they can be mixed together without conflicting.

flutter_sound as you say has a different philosophy since it is aiming to be a monolithic audio plugin that meets all of your audio needs in one plugin (both recording and playing). You could fork that project and extract just the recorder out of it, but then you may still need to deal with its LGPL license which can make it [a bit complicated](http://answers.google.com/answers/threadview/id/439136.html) to release on the app stores.

At the moment, the best candidate for an audio recorder that would fit into this audio ecosystem of non-conflicting plugins appears to be [record](https://pub.dev/packages/record). Another would be [microphone](https://pub.dev/packages/microphone), but it doesn't yet have enough platform support. So probably the best way forward would be to use one of those plugins and contribute bug reports and feature requests for anything those projects are currently lacking.

**Comment by ryanheise** [comment]
I will close this for the time being since I don't personally have a plan to work on audio recording, but would encourage people to support some of the other single-responsibility plugins such as those mentioned in my previous comment, so that they get more momentum behind them.
