### ISSUE TITLE
Duration API does not work on iOS

### ISSUE THREAD

**Issue by flutternoob** [ryanheise/just_audio#618]
The duration API does not work on iOS simulator or device. I am targeting iOS 13. I need to use the just_audio library only to get the duration of the audio file before the audio file is played. Another library, ```audioplayers```, is being used to perform playback and seek functions. However, ```audioplayers``` cannot get the duration of the file before it is played. I would have used ```just_audio``` for playback and seek functions but I ran into problems for background playback.

**Which API doesn't behave as documented, and how does it misbehave?**
The duration API. I am using the following code:
```
Duration? _duration;

@override
  void initState() {
    super.initState();
    _initAudioPlayer();
  }

Future<void> _initAudioPlayer() async {
    _duration = await _audioPlayer.setUrl(widget.audioFileDetails!["filePath"]);
    setState(() {
      durationString = "${_duration!.inMilliseconds}";
    });
  }
```

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
1. Create a StatefulWidget
2. In the ```initState()``` method call a Future that gets the duration of the locally stored audio file
3. Use a ```print``` statement in the Future to display the duration of the audio file in milliiseconds
4. ```print``` statement gives an output of 0 instead of the file's duration along with the below error message

**Error messages**

```
Performing hot reload...                                                
Reloaded 1 of 1547 libraries in 735ms.
flutter: 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: (-1002) unsupported URL
#0      AudioPlayer._load (package:just_audio/just_audio.dart:778:9)
<asynchronous suspension>
#1      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1346:28)
<asynchronous suspension>
#2      AudioPlayer.load (package:just_audio/just_audio.dart:708:26)
<asynchronous suspension>
#3      AudioPlayer.setAudioSource (package:just_audio/just_audio.dart:683:18)
<asynchronous suspension>
#4      _ULTAudioLecturesPlaybackBodyState._getDuration (package:united_lodge_of_theosophists/screens/audio_lectures/audio_lectures_playback_body.dart:66:29)
<asynchronous suspension>
#5      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart)
<asynchronous suspension>
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**

**Flutter SDK version**
```2.5```
insert output of "flutter doctor" here
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-arm, locale
    en-IN)
    • Flutter version 2.5.3 at /Users/ankushlaxman/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/ankushlaxman/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • 94D8BE46-AF15-43BC-A7E5-392DDD72BFDE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 96.0.4664.110
```

**Additional context**

**Comment by ryanheise** [comment]
Will reopen once you complete the form according the instructions.

I'm quite surprised though that you gave me code instructions under the section that explicitly says "not code". And then under the previous section where it explicitly asks for code, in the form of a minimal reproduction project, you ignored the instructions.

**Comment by ryanheise** [comment]
> **Which API doesn't behave as documented, and how does it misbehave?**
>
> The duration API.

You missed the part "how" it's behaviour differs from the documentation.

**Comment by flutternoob** [comment]
Hi @ryanheise , thank you for getting back to me and sorry for the mix up. In my project, I have to first download the audio file from the internet and then get the file duration from the locally stored audio file and display its duration in the UI. Moreover, I am using an M1 Mac with which I have been running into issues with XCode. If you try to clone a repository to reproduce the above mentioned error, on an Intel Mac, you could run into problems to get the app to work. See this issue for more information on this:

https://github.com/flutter/flutter/issues/91217

Because, of these two reasons, I thought it would be unnecessary to create a whole new project for a few lines of code that is not working.

As for the "how" part of the error, the duration read from the file using the duration API is 0 milliseconds, instead of displaying the actual duration of the audio file (on iOS only, works great on Android). This can cause a problem when using a Slider for example since you will get a ```value >= min && value <= max``` error. Thanks

**Comment by ryanheise** [comment]
How is the behaviour different from what is documented? Please be precise. Can you quote the documentation saying one thing and the actual behaviour being different? I don't need the long back story, just the specific things that the instructions are asking for.

**Comment by ryanheise** [comment]
The documentation for each API is here:

* [setUrl](https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setUrl.html)
* [setFilePath](https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setFilePath.html)
* [setAsset](https://pub.dev/documentation/just_audio/latest/just_audio/AudioPlayer/setAsset.html)

Please check the documentation, and then update the first section of your bug report with something like this (if actually accurate):

> The documentation for `setUrl` says that if I give it a URL argument, it will return the duration. But it doesn't.

**Comment by flutternoob** [comment]
@ryanheise  , updated the issue

**Comment by ryanheise** [comment]
Wait, are you using `setFilePath` now? You now mention `setFilePath` in your bug report which you never mentioned before. I still don't have your minimal reproduction project to be able to verify any of what you're saying, but the small amount of code you HAVE supplied only shows `setUrl` passing in what appears to be a file path instead of a URL, but without being able to see all of your reproduction project I don't know if that's really the case. Furthermore, if the method argument is correct, it still matters what the file contents are since it may be that. You're making it quite difficult for me by intentionally skipping over the information I said I needed in the instructions. If you are using `setFilePath` and passing in a file path, or if you are using `setUrl` and passing in a URL, then please clarify that and also as I have already asked, provide a minimal reproduction project that demonstrates the issue. But if you are using `setFilePath` passing in a URL, or using `setUrl` passing in a file path, then I don't see how you could fill in the first section of the bug report because you yourself aren't fulfilling the contract by passing in correct arguments according to the documentation.

And that is the whole purpose of the first section of the bug report. It forces you to check whether this really is a bug or not, so that you don't overburden to developer's time. I have already spent more than an hour on this issue and all of that time has been spent trying to explain things that I have already said in the instructions (in case you're wondering why this is a burden, I have some physical limitations when it comes to using computers. It's really unfortunate that people don't just take a little more time to carefully fill in the bug report as per the instructions and help make things easier for me.)

**Comment by flutternoob** [comment]
After seeing your reply about which documentation to specify, i tried using setFilePath as well with the same result mentioned in the issue.

And while I can understand that you may have physical limitations to using the computer, please bear in mind that I have mental limitations doing any kind of task. So, i am truly sorry if the bug report is not as expected

**Comment by ryanheise** [comment]
Ok let's finish here. You can't help me and I can't help you.

**Comment by flutternoob** [comment]
Except for the reproducible project, I gave you everything you needed. I find your refusal to help strange and disturbing

**Comment by ryanheise** [comment]
The minimal reproduction project is 90% of what I need to act.

I literally "can't" help, because you aren't providing me with the necessary information requested in the submission form, where the reproduction project itself is the main thing I need for reasons explained above and in the contributing.md document. Likewise, you said you actually can't help me because of mental limitations with what I need. In summary, you "can't" help me to help you. Suffering multiple chronic health conditions is not fun and I'm dealing the best I can with the pain so that I can continue to productivity serve society, I wouldn't my situation on anyone, but it sounds like you are going through something equally debilitating in your life.

But the fact remains that this issue is literally unable to proceed until the necessary information is provided, and you are unable to provide that. If at this point you still expect me to solve your problem with only 10% of what I need, it seems like you don't actually care how difficult it is to fix bugs. Bugs are already difficult enough to fix as it is, it is even much harder given my life circumstances, but it's not as though I need the challenge of you making it even harder by expecting me to do all of the work without being able to see more than 10% of what I actually need to solve the problem.

I regretfully am locking this issue since any further pleas to fill out the bug report as per my instructions will not be fruitful since it has been established that you are not capable providing the reproduction case with the specific file that causes a zero duration.
