### ISSUE TITLE
Volume is not synchronized with the system volume

### ISSUE THREAD

**Issue by liri2006** [ryanheise/just_audio#627]
**Which API doesn't behave as documented, and how does it misbehave?**
volumeStream, setVolume

**Minimal reproduction project**
"The example"

**To Reproduce (i.e. user steps, not code)**
1. Go to Volume section -> volume is always at 1.0 level even if is set different by hardware buttons.
2. Change volume -> volume in the app will change, but system volume would stay unaffected.
3. Change volume with hardware buttons -> volume level slider will not be affected. 

**Expected behavior**
There should be a possibility to have same volume as the app wide one, and a possibility to change it with hardware volume buttons.

**Flutter SDK version**
```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1415], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
```

P.S. Thank you for the hard work, this plugin is impressive!

**Comment by ryanheise** [comment]
Hi @liri2006 ,

> **Which API doesn't behave as documented, and how does it misbehave?**
> volumeStream, setVolume

To me it seems to be behaving as documented, since the documentation does not say anything about synchronising with hardware buttons. Those are for controlling the phone's volume, not this plugin's volume, so you may need to find another plugin to deal with that.

**Comment by liri2006** [comment]
Hi @ryanheise, thanks for the response. 
Would it make sense then to convert this issue into a feature request? 
Reasoning - all the audio player apps I've used do have volume controls in sync with the app (Spotify, Audible, etc), so it would be nice if everything needed for production ready audio app was in a single package.

**Comment by ryanheise** [comment]
It doesn't belong in just_audio since the system volume is not a feature of the player, it is a feature of the system. You can have multiple instance of `AudioPlayer`, each with its own independent volume. Setting the volume of one player does not affect other players. What you're talking about is being able to change the volume of the system rather than a particular player. This plugin only concerns itself with the player. My philosophy for plugin design is to prefer multiple plugins, each managing a single responsibility, rather than having one plugin that does everything. This philosophy is explained and justified in the README, and is in fact the reason why I used the word "just" in the plugin name. It is an attempt to convey this approach.

**Comment by liri2006** [comment]
@ryanheise Understood, thanks a lot for taking the time to explain :)
