### ISSUE TITLE
Please auto set URL for / started string in IOS, so we get file://{path}/ automatically just as Android.

### ISSUE THREAD

**Issue by xqiu** [ryanheise/just_audio#628]
**Is your feature request related to a problem? Please describe.**
I spent a lot of time finding why just_audio could not play IOS local file path, where in android it does not have problem.

In Android, SetAudioPath for local file can be passed with /path/ string
In IOS, SetAudioPath for local file can only be passed with file://path/ string.  It was OK a year ago with old just_audio releases.

**Describe the solution you'd like**
Please auto set URL for / started string in IOS, so we get file://{path}/ automatically just as Android.

**Describe alternatives you've considered**
Otherwise, we need clear documentation for this.

**Additional context**
I think this is related to https://github.com/ryanheise/just_audio/issues/616

**Comment by ryanheise** [comment]
What is SetAudioPath? If you mean setFilePath, I do not understand how you're saying:

> In IOS, SetAudioPath for local file can only be passed with file://path/ string.

That's not right, it should be the opposite: if you want to use setFilePath, you should pass in the path, and I think that's a straightforward reading of the documentation which should not be confusing. It is a bit confusing that on Android, you can pass a file path into setUrl, because the documentation does tell you you should pass in a URL and not a file path. But if you use all methods according to their documentation, it should work correctly. The Android behaviour is historical, that's the way Android works under the hood, but Android's behaviour should not be considered a role model.

**Comment by xqiu** [comment]
I meant for different AudioSource(Uri.parse(xxx)) functions.  

Your explanation make sense.  Thanks. 

I just need to make sure I use different code path when download a file and play it later.
