### ISSUE TITLE
how to assign artUri from local 

### ISSUE THREAD

**Issue by AcarFurkan** [ryanheise/just_audio#640]
.mp3 work good but l couldnt assign artUri from local what should l do ??
![error two](https://user-images.githubusercontent.com/65075121/151854406-3b7c949a-0de0-457a-8a67-00598d5cf39b.png)

**Comment by AcarFurkan** [comment]
omg l dont like bot

**Comment by ryanheise** [comment]
@AcarFurkan I don't like it when people have no respect for the instructions, and then complain when they don't get what they want after ignoring the instructions.

**Comment by AcarFurkan** [comment]
@ryanheise  l got you but l send a photo about problem and  it is just a question about arturi. it isnt clear.l searched a lot and l coundt find. also l like your package thank you.

**Comment by ryanheise** [comment]
No buts, please follow the instructions or please don't post at all. I like the keep things organised since there are too many issues to deal with otherwise. Thank you.

**Comment by AcarFurkan** [comment]
if you dont understand my question because of l didnt follow instructions okay but if you understand or dont read at all you are just rude....

**Comment by ryanheise** [comment]
If you don't read the instructions at all, and indeed "disregard" the instructions, even after I have repeatedly pointed you to the instructions, then perhaps you are confused about what it means to be rude.

When you clicked on the "New issue" button, there were instructions, and an option to ask a question. You instead chose the option to post a bug which had the following instructions. Note the very first line says "All sections below must be completed". For you to see that and then just completely delete it all and then expect me to answer question which does not belong in my issues database because this is not actually an "issue", and for you then to ignore the bot's message which was entirely informative with a quip "omg l dont like bot", that is what I consider rude. If you don't actually care what the project author requires in order to post to this board, then you are not contributing in a positive way and I suggest you go elsewhere.

```
<!--    ALL SECTIONS BELOW MUST BE COMPLETED   -->
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Error messages**

If applicable, copy & paste error message here, within the triple quotes to preserve formatting.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [e.g. chrome, safari + version]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]

**Flutter SDK version**

insert output of "flutter doctor" here

**Additional context**
Add any other context about the problem here.
```

I will lock this issue since time spent debating this with you is time taken away from working on the actual issues.
