### ISSUE TITLE
Merge buffering into AudioPlaybackState

### ISSUE THREAD

**Issue by suragch** [ryanheise/just_audio#66]
There may be a programmatic reason for putting `buffering` into `FullAudioPlaybackState` instead of `AudioPlaybackState`, but it doesn't seem to make sense from a UX perspective.

I recommend moving `buffering` to the `AudioPlaybackState` enum, even if it is a breaking change.

**Comment by ryanheise** [comment]
Hi @suragch , you can search past issues to find a discussion of how this decision came about, but the buffering state truly is orthogonal to the play/pause state. The plugin can be buffering in a number of different states: while connecting to the URL, while playing, and while paused. It should be possible to show in the UI whenever the plugin is buffering, but it should also be possible to distinguish for example between when the plugin is buffering while paused and buffering while playing. I do not consider it elegant to have multiple different buffering states in the enum when you could use a product of the playback states and the buffering states.

ExoPlayer has also realised that the naive state model that people "think" they want to use is not really useful enough, so they have also done something similar but a bit different. I think the approach I've taken is a bit simpler than theirs but if I were to ever change the state model, ExoPlayer's model would be my second choice since it at least doesn't eliminate any state information.

**Comment by suragch** [comment]
That explanation makes a lot of sense. Thank you. It would be great to add a similar explanation to the in-code documentation. Currently `FullAudioPlaybackState` has no documentation at all and `AudioPlaybackState` only has a single line that doesn't describe much more than the class name already says.

**Comment by ryanheise** [comment]
Thanks, I have just added documentation.
