### ISSUE TITLE
Null duration on all platforms for audio recorded with Opus WEBM codec

### ISSUE THREAD

**Issue by jcblancomartinez** [ryanheise/just_audio#689]
**Which API doesn't behave as documented, and how does it misbehave?**
setAudioSource returns null duration for audio recorded with Opus WEBM codec.

**Minimal reproduction project**
[Link](https://drive.google.com/file/d/1qbAbKA7wPzronqhuSJPzrxaGVLkPqsN-/view) to audio.

**To Reproduce (i.e. user steps, not code)**
1. Try to get duration for [this audio](https://drive.google.com/file/d/1qbAbKA7wPzronqhuSJPzrxaGVLkPqsN-/view).
2. Duration is null.

**Expected behavior**
I would expect duration to be other than null. When playing the audio locally, my audio player shows a duration of 2 seconds.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All

**Flutter SDK version**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on Ubuntu 20.04.3 LTS 5.13.0-37-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

• No issues found!
```
Thanks.

**Comment by ryanheise** [comment]
> **Which API doesn't behave as documented, and how does it misbehave?**
> setAudioSource returns null duration for audio recorded with Opus WEBM codec.

I would disagree with you about WebM behaviour being documented. just_audio merely exposes the codec support of the underlying platform; Not all platforms support the same codecs, and in particular, iOS famously does not support WebM.

As for the ability to detect the duration, this is less about platform support and more about the configuration of your web server (in combination with the encoding of the file). For encodings where the duration metadata is not stored at the beginning of the file, In order to detect the duration, all platforms need the ability to jump to the end of the audio file to read that metadata block, and this requires your server to support range requests. Looking at your supplied URL, I noticed that range requests are not accepted, so there is no way for any client, whatever the platform, to read that duration metadata if it's at the end of the file, without downloading the entire file first, but as you can see, the platforms prefer the approach of allowing you to start playing the audio immediately before waiting for the entire file to download, and that means the duration will be unknown at the time the audio is "ready" to be played. If it is not practical for your web server to support range requests, then you will need to re-encode your audio in a way that is more appropriate for that scenario, i.e. with the duration metadata stored at the beginning of the file. But in this era, you probably should support range requests on the server.

**Comment by jcblancomartinez** [comment]
Thanks for the clarification.

It makes sense.
