### ISSUE TITLE
iOS Safari Red mic does not go away 

### ISSUE THREAD

**Issue by bdytx5** [ryanheise/just_audio#706]
**Which API doesn't behave as documented, and how does it misbehave?**
stop() method does not remove the red mic at the top of the screen in safari for iOS. The red icon remains there even after stopping the recording and closing the browser. 

**Minimal reproduction project**
The example 
see https://dsports-6ab79.web.app/#/
also see https://github.com/llfbandit/record/issues/53
**To Reproduce (i.e. user steps, not code)**
Steps to reproduce the behavior: go to https://dsports-6ab79.web.app/#/ on ios with safari 

1. clone the example 
2. Host it
3. Open in ios Safari web browser 
**Error messages**
none, the red mic just doesnt go away after stopping the recording 

**Expected behavior**
The red mic at the top of the screen should go away after clicking stop recording. 

**Screenshots**
  n/a

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS + version]
 - Browser [safari on iOS, all known versions from what I can tell]

**Smartphone (please complete the following information):**
 - iPhone X 
 - OS: [ iOS15]

**Flutter SDK version**
Flutter 2.8.1 • channel stable 

**Additional context**
no

**Comment by ryanheise** [comment]
Can you please fix your bug report by following the instructions for each section?

**Comment by bdytx5** [comment]
Ok, i added more info

**Comment by ryanheise** [comment]
I still don't see the minimal reproduction project. Your link is to a compiled app so I can't see the code or clone your repository.

Also, I'm not clear on what you are saying is caused by just_audio. This plugin doesn't actually use any APIs relating to the microphone. I therefore don't think there is anything I could do for you within this plugin to affect that positively or negatively.

**Comment by bdytx5** [comment]
Ok, my mistake.
