### ISSUE TITLE
Problem running the app from the beginning when we close the app and open it again while the music is running in the background by the just_audio_background package

### ISSUE THREAD

**Issue by AhmadFalahian** [ryanheise/just_audio#724]
**Is your feature request related to a problem? Please describe.**
I designed a music player application that has a music player page, I used the[ just_audio_background](https://pub.dev/packages/just_audio_background) package to play the song in the background. Suppose the music player page is A and I go to page B and close the app. Now when the music is running in the background, when I close the app and run it again, page B opens while the first page where the app opens Be A page.

**Describe the solution you'd like**
It must be opened after closing the application and reopening it on the first page, ie A.

Describe alternatives you've considered

**Comment by ryanheise** [comment]
You deleted this section:

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Comment by AhmadFalahian** [comment]
> You deleted this section:
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

Comment updated

**Comment by ryanheise** [comment]
Do you think it would be a good idea to write below that section heading a clear and concise description of any alternative solutions you've considered? Or may not, you don't think that would be a good idea to fill in that section?

**Comment by AhmadFalahian** [comment]
I have no idea about this solution, I have just stated what I mean

**Comment by ryanheise** [comment]
This behaviour is expected because the app is still running in the background and remembers its state. The YouTube app also works this way.

If you want a different behaviour, you need to control that in your app, and you don't require support from this plugin to do that. The purpose of the "Alternative solutions" section is for you to think whether you could solve it another way, and so I would suggest first thinking about updating your own app code to explicitly reset its state to the first page when your app moves into the background. Use Flutter APIs to do that, not just_audio_background APIs.

**Comment by ryanheise** [comment]
I'll close this feature request in favour of it being handled in the app rather than the plugin. But if you are able to demonstrate that it must be added to the plugin, let me know below and I'll reopen.
