### ISSUE TITLE
iOS streams weird behavior, Android is fine though

### ISSUE THREAD

**Issue by yadaniyil** [ryanheise/just_audio#726]
**Which API doesn't behave as documented, and how does it misbehave?**
With the same audio URL, android works fine, but iOS has some problems. I can describe them as not getting duration and position in streams. On iOS audio starts playing, but does not show the total duration and the slider is not moving, because the current position is not returning in the stream. What's interesting is that the current position is returned only when you pause the audio.

**Minimal reproduction project**
Link to fork: https://github.com/yadaniyil/just_audio
Build the just_audio/example

**To Reproduce (i.e. user steps, not code)**
1. Run the android, everything works fine
2. Run the iOS, and see that while audio is playing the duration is zero until you pause that audio. 
3. Pausing the audio will show the current stop duration.

**Error messages**
No error messages were found. 

**Expected behavior**
Expected to work as on Android. The current duration is updated every second and the slider is moving.

**Smartphone (please complete the following information):**
 - Device: [Android emulator pixel 3a]
 - OS: [API 32]
 - Device: [iOS simulator iPhone 13]
 - OS: [iOS 15.4]

**Flutter SDK version**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.2.1 21D62 darwin-arm, locale en-UA)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2021.1)
[!] Android Studio
    ✗ Android Studio not found at ../android/Contents
[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
[✓] VS Code (version 1.67.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
**Additional context**
The audio link that I've changed might be expired in a week, so please let me know if I need to update the example.
Thanks for the lib, it's really helpful, especially background, and very easy to set up and use.

**Comment by ryanheise** [comment]
I'm not at my computer right now but can you tell me the response headers from the server hosting that file? You will want to check that they meet iOS's requirements.

**Comment by yadaniyil** [comment]
Thanks for the quick answer. This is the headers from DevTools, but unfortunately, I can't see it it's incompatible with iOS.

![image](https://user-images.githubusercontent.com/16175106/168537225-7cfbfe9c-4c1a-4a39-a546-6b94fa0d1131.png)

**Comment by ryanheise** [comment]
Hmm, why is the content-type `application/json` for an mp3 file?

**Comment by utkarshshendge** [comment]
@ryanheise I am also facing this issue

**Comment by utkarshshendge** [comment]
<img width="1016" alt="Screenshot 2022-05-16 at 9 54 30 PM" src="https://user-images.githubusercontent.com/57677520/168639427-0be2d245-c52c-4314-a206-3bc56fc5b642.png">
@ryanheise Please have a look

**Comment by MANISH007700** [comment]
@ryanheise I am facing the same issue on IOS. 
@yadaniyil did you find a solution.

**Comment by ryanheise** [comment]
@utkarshshendge your response headers look fine. I notice the content-type is audio/m4a but I'd need to look into the file to know what it's real format is. is your problem exactly the same? Are you finding that the "position" stream is not updating? That would be very unusual because I think the position should update regardless of the format or headers. As for duration, that depends on the actual format of the file and the headers. Your headers seem fine, but I'm not sure about the format since I can't see your file (the link expired).

@MANISH007700 As you can see, I am repeatedly asking each person who reports this the same questions over again. You can save me time by reading the above comments, and then providing all of the information I have been asking for.

**Comment by yadaniyil** [comment]
It seems like my backend does not send the required for iOS headers, that's why on iOS I don't have the current audio position and duration, but on Android I do.

**Comment by ryanheise** [comment]
@yadaniyil yes, that is the most common cause for problems on iOS. Have you confirmed that fixing the headers fixes your issue?

**Comment by yadaniyil** [comment]
@ryanheise not yet, waiting for actions on the backend side, maybe this week

**Comment by ryanheise** [comment]
@yadaniyil were you able to confirm that correct server headers solved the iOS issue?

**Comment by mzeeshan-whizpool** [comment]
@yadaniyil Can you confirm which iOS header is needed to display properly seekbar and timer?

**Comment by RamiHI** [comment]
Hello, I have the same problem when I try to play a sound from the fire base, is there a solution?

**Comment by xiaohucode** [comment]
use AudioSource.uri no problem

use LockCachingAudioSource,👇👇
On ios platform: [Content-Type: application/octet-stream] Failed! PlayerException ((-11828) Cannot Open)??


![IMG_1569](https://user-images.githubusercontent.com/24434389/198655406-e4948bf5-43ab-48fb-b0c2-fa98f574ced4.PNG)

**Comment by ryanheise** [comment]
I am closing this issue since I haven't heard back regarding the headers. If it is the headers, then it's not a bug in just_audio, it's a server side issue.

If anyone else has a bug to report, please open a new issue. Please note that if you have commented above already, your issue is not necessarily the SAME issue as the one originally reported here, and posting a "me too" comment will probably not help me to solve your specific issue. It needs its own bug report.
