### ISSUE TITLE
Cannot build release for Android with 0.9.22

### ISSUE THREAD

**Issue by mark8044** [ryanheise/just_audio#740]
using `flutter build apk` and `assembleRelease` fails on `0.9.22` (and all the 0.9 series) but works fine with `0.8.1`

Error that I get is:
```
Execution failed for task ':just_audio:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users//.gradle/caches/transforms-3/0a679862f6c55d82fb9a949f1fd4603f/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

```

**Comment by ryanheise** [comment]
I guess my instructions were not clear...

**Comment by mark8044** [comment]
@ryanheise Sorry, which instructions, for the bug report?  Theres no real code to show it, purely a build problem

**Comment by ryanheise** [comment]
Well, the official example works fine as I can't reproduce the bug. That is why you must provide me with some code that demonstrably won't build due to this error. There's also a whole bunch of other things I need such as your Flutter versions platform versions, etc. I really don't want to have to ask you this here, that is why I wrote those instructions in the first place. Can't you just please take the time to read and follow them?

**Comment by mark8044** [comment]
> Well, the official example works fine as I can't reproduce the bug. That is why you must provide me with some code that demonstrably won't build due to this error. There's also a whole bunch of other things I need such as your Flutter versions platform versions, etc. I really don't want to have to ask you this here, that is why I wrote those instructions in the first place. Can't you just please take the time to read and follow them?

Got it
Will file a new bug momentarily and try my best to fill out as much useful information as possible
