### ISSUE TITLE
How to set the adio quality when I play a radio stream URL

### ISSUE THREAD

**Issue by ntnhan94** [ryanheise/just_audio#748]
**To which pages does your suggestion apply?**

https://pub.dev/packages/just_audio

**Quote the sentences(s) from the documentation to be improved (if any)**

```
final player = AudioPlayer();
var duration = await player.setUrl('https://foo.com/bar.mp3');
```

**Describe your suggestion**
Could you mention clearly how to set (or control) the audio quality. I ask this because I usually got the interruption when I play a radio stream in the background. I guest it is because of the slow network and so I would like to have an option to set audio quality when downloading from network resource.

Thank you so much.

**Comment by ryanheise** [comment]
There is no way to control that, so there's nothing to document. But if you'd like options, please make a feature request. Before doing so, please also search past issues to avoid a duplicate, because I believe at least on Android (although you didn't specify a platform) there are ways it would be possible to provide such an option and I believe it has been asked before.

**Comment by ntnhan94** [comment]
Okie thanks for your answer. I will search and make a feature request later.
