### ISSUE TITLE
Ignore just_audio_background possibility

### ISSUE THREAD

**Issue by nzackoya** [ryanheise/just_audio#749]
**Is your feature request related to a problem? Please describe.**
I need a way to play a background sound without the notification while main sound is playing. Is there a way to set the player to ignore just_audio_background to not face "just_audio_background supports only a single player instance"?

**Describe the solution you'd like**
I'd like to have something like AudioPlayer(useJustAudioBackground: Bool)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ryanheise** [comment]
I'm sorry I don't understand what you're asking. But if you're asking to play audio in the background without a notification, this is not allowed on Android. The operating system requires any app running in the background to present a notification so that the user is aware of what app is causing that noise to happen. I can't change that.

As for the single player instance rule, you are muddling up two separate questions, since that is really a separate question. There is no problem having multiple instances if you use audio_service directly, and that is why the just_audio_background says that for more advanced requirements, that's what you should do.

**Comment by nzackoya** [comment]
> I'm sorry I don't understand what you're asking. But if you're asking to play audio in the background without a notification, this is not allowed on Android. The operating system requires any app running in the background to present a notification so that the user is aware of what app is causing that noise to happen. I can't change that.
> 
> As for the single player instance rule, you are muddling up two separate questions, since that is really a separate question. There is no problem having multiple instances if you use audio_service directly, and that is why the just_audio_background says that for more advanced requirements, that's what you should do.

I need to play a music using all the features of just_audio and just_audio_background, but also play a sound in background, simply without any features except start and stop. Is there a way to start 2 players, but one of them set to ignore just_audio_background. If I use only audio_service, then I'll have to implement everything from just audio. Can I create like just_audio AudioPlayer and audio_service AudioPlayer so they so they play simultaneously?

**Comment by ryanheise** [comment]
Did you read the part of my answer before "... that's what you should do."?
