### ISSUE TITLE
[Bug] Audio session doesn't end when playpack is done.

### ISSUE THREAD

**Issue by adiPumba** [ryanheise/just_audio#766]
Hi,

I'm using this package with the option of ducking others while playing my app sounds.
The ducking works well when starting the playback, but doesn't release it when the playback is done.

In audio_session we discussed about that:
https://github.com/ryanheise/audio_session/issues/27

Thanks.

**Comment by ryanheise** [comment]
> ALL SECTIONS BELOW MUST BE COMPLETED

Please don't ignore this, it was the very first line of the instructions.

But in any case, you will not be able to qualify this as a bug in the first section of the bug report because as I told you in https://github.com/ryanheise/audio_session/issues/66#issuecomment-1164157345 just_audio chooses not to deactivate the audio session. It is only a bug if the documentation were to say that just_audio intends to deactivate the session and then fails to. just_audio never intended to do that anyway, it chooses not to deactivate the session. As I already implied in that other issue, you can deactivate the session yourself by using audio_session. That is your own choice, but this plugin is not going to do that for you. If audio_session does not actually work to that end, you should be reporting the bug over there. I actually already had this conversation with you over there, but suggested at the end that this is likely just the inherent behaviour of Apple's API, and there is nothing I can do to change Apple's behaviour.

**Comment by adiPumba** [comment]
@ryanheise 
Thanks, I will chheck it.
By thw way, is there any indication with just_audio to know when the playback is done? 
(So I will try to manually end the session with audio_session)

**Comment by ryanheise** [comment]
Is my documentation that bad? If so, please submit a documentation request.
