### ISSUE TITLE
Does anyone even answer Stackoverflow questions ?

### ISSUE THREAD

**Issue by elvisgn** [ryanheise/just_audio#786]
Hi,
I went by the community guidelines and posted my question on Stackoverflow with the tag. But doubt anyone is even reading the post.

Request support with the below:
https://stackoverflow.com/questions/73202265/errors-on-setsource-options

Thanks,
Elvis.

**Comment by ryanheise** [comment]
I didn't initially read this issue, it goes straight to my spam because you ignored the instructions by not following the correct template structure. Stack overflow is a separate community for community support. Nobody is guaranteed to help you in this open source world, one person can't do every role so if nobody steps up to help you, then perhaps you yourself can step up and be a member of that community that investigates the answers yourself and then helps others. Checking in stack overflow, it appears that I just happened to engage with you within one day of your posting that question which is both rare and fast, yet you seem to be expecting the speed of a 24-hours all day all night service. Furthermore, even though it appears I engaged you there very quickly, you never answered my question after weeks of waiting. I guess you expect help as a given but don't appreciate when someone puts in the effort to do that.
