### ISSUE TITLE
startForegroundService() not allowed due to mAllowStartForeground false

### ISSUE THREAD

**Issue by leetomlee123** [ryanheise/just_audio#834]
[sentry link](https://sentry.io/share/issue/cba46f88c813412f9e3f9919dba18e3f/)

**Comment by leetomlee123** [comment]
random occor

**Comment by ryanheise** [comment]
1. Do I really need to submit a minimal reproduction project for a bug? A: Yes. I prioritise bugs secondarily on how many people are affected, and primarily on whether the bug report is complete, in the sense that it enables me to immediately reproduce it and start working on a fix. If a bug is important to you, the best thing you can do is to provide all requested information ASAP so that I can start looking into it ASAP.
2. I think I supplied all required information, so did the bot make a mistake? A: The bot only checks the section headings, so when you post a new issue, make sure you leave the section headings intact. (Note that because of this, it is even possible to trick the bot by including only the section headings, and then not providing the requested information under each heading. This is frowned upon, and the issue will be closed manually.)
