### ISSUE TITLE
iOS: Unexpected platform error: AVPlayerItem.Status.failed

### ISSUE THREAD

**Issue by sauravdpl** [ryanheise/just_audio#849]
**Which API doesn't behave as documented, and how does it misbehave?**
Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.

**Minimal reproduction project**
Provide a link here using one of two options:
1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
2. If the unmodified official example already reproduces the bug, just write "The example".

**To Reproduce (i.e. user steps, not code)**
1. Added audio player to class
2. Click on play button 

**Error messages**
flutter: Unexpected platform error: AVPlayerItem.Status.failed
```

**Expected behavior**
A clear and concise description of what you expected to happen.


**Screenshots**
If applicable, add screenshots to help explain your problem.


**Smartphone (please complete the following information):**
 - Device: [iPhone12 max pro simulator]
 - OS: [14.5]
 - Device:[iphone 7 plus real device]
 - OS:[14.2]

**Flutter SDK version**
Flutter 3.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cd41fdd495 (4 months ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2
```
insert output of "flutter doctor" here
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.6 21G115 darwin-x64, locale
    en-NP)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.2)
[✓] VS Code (version 1.64.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.

**Comment by ryanheise** [comment]
> **Which API doesn't behave as documented, and how does it misbehave?** Name here the specific methods or fields that are not behaving as documented, and explain clearly what is happening.
> 
> **Minimal reproduction project** Provide a link here using one of two options:
> 
>  1. Fork this repository and modify the example to reproduce the bug, then provide a link here.
>  2. If the unmodified official example already reproduces the bug, just write "The example".
> 
> **To Reproduce (i.e. user steps, not code)** Steps to reproduce the behavior:
> 
>  1. Added audio player to class
>  2. Click on play button
>  3. See error

Are you seriously going to just neglect each section without providing the requested information? Right after posting another issue where you outright deleted and ignored the instructions?

This is what you were told already in response to your last issue:

> The bot only checks the section headings, so when you post a new issue, make sure you leave the section headings intact. (Note that because of this, it is even possible to trick the bot by including only the section headings, and then not providing the requested information under each heading. **This is frowned upon, and the issue will be closed manually**.)

I put the last sentence in bold, because you did it anyway. Hence, I'm frowning upon it, and closing manually.

**Comment by sauravdpl** [comment]
i have not forked your project just used the code as per the example, and now it throwing an Unexpected platform error: AVPlayerItem.Status.failed on ios when calling the play function. if you cannot provide the solution then what is the purpose of your package if  does not  work propley

**Comment by ryanheise** [comment]
I think you've missed the point which is that I "can" investigate and fix bugs when people submit valid bug reports. But it is impossible for me to investigate a bug with as little information as you have provided. You have chosen to make things harder for me (and in this case impossible for me), so don't expect a solution to be forthcoming. I would hazard a guess that this is not actually a bug (not that you would care, since you didn't bother filling in the first section which is designed to qualify your report as a legitimate bug.)

Secondly, you seem like you feel as though you're entitled to receive help. And so even when you make such a minimal effort to submit a bug report, leaving out all the sections I need, that I should STILL try to fix the (supposed) bug with both hands tied behind my back. This is unfortunate since I already have that issue due to my health condition.

The instructions are in place because it is not easy for me to do what I do, and I need your help to submit bugs in a way that makes them easier for me to manage them. I can only help those who are equally willing to help me.
