### ISSUE TITLE
Plugin is not documented for firebase storage file use in iOS

### ISSUE THREAD

**Issue by prateekmedia** [ryanheise/just_audio#904]
**To which pages does your suggestion apply?**

- https://github.com/ryanheise/just_audio/blob/532e6f9d3a81d7c70507fd80ca94ac63e627c3f6/just_audio/lib/just_audio.dart#L737

**Quote the sentences(s) from the documentation to be improved (if any)**

None, Documentation needs to be updated for that maybe it is because of the headers.

**Describe your suggestion**

Add related documentation for using the plugin with firebase storage files like:
https://firebasestorage.googleapis.com/v0/b/besomethinggreat-a89b2.appspot.com/o/stories%2Fcontent%2F1664942224930mp3?alt=media

**Comment by ryanheise** [comment]
Your URL doesn't have a valid content type. Here are your server headers:

```
x-guploader-uploadid: ADPycdvUCNg7zc8wJs3qRWLcClrDr47daASKGHnmrBLudS2RGZujm2sAmuAwKDnZW1CFeebQCL3fxe2BdQT1bc9e5tceWA
expires: Thu, 22 Dec 2022 00:37:57 GMT
date: Thu, 22 Dec 2022 00:37:57 GMT
cache-control: private, max-age=0
last-modified: Wed, 05 Oct 2022 03:57:07 GMT
etag: "5f35ab2151965e0f421ae05c64dfffe7"
x-goog-generation: 1664942227015980
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 3350714
x-goog-meta-firebasestoragedownloadtokens: d93a0726-80fc-4e85-91d7-7ec2b1c0b414
content-type: application/octet-stream
content-disposition: inline; filename*=utf-8''1664942224930mp3
x-goog-hash: crc32c=dscJTg==
x-goog-hash: md5=XzWrIVGWXg9CGuBcZN//5w==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 3350714
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

As per the way the web works, clients read the content type header to understand how to decode and render the media. If you just broadcast that it is `application/octet-stream`, which is what you're doing, then iOS will not recognise that as a valid format.


This is generally not a problem with most URLs out there because people who publish their own websites learn how to publish URLs with the correct HTTP header configuration. In your case, you did not set up your server correctly.

I can add a troubleshooting section for common mistakes that people make, but this will be along the lines of asking you to just check that when setting up your own web server, that you set it up correctly with correct headers. You will still have to consult the documentation of whatever software you're using on the backend to learn how to use THAT product correctly. E.g. If you're using firebase or AWS or some other cloud service provider, consult the documentation for the relevant service. If you are hosting your own web server, such as Apache or Nginx, consult its documentation on how to issue correct headers. If you are writing your own backend server where the HTTP responses are generated by your own backend code, then write correct code.

**Comment by prateekmedia** [comment]
Does that mean specifying content type manually in headers of AudioSource work?

**Comment by ryanheise** [comment]
No.

**Comment by prateekmedia** [comment]
I have fixed it on my end by renaming all to .mp3, It's now your choice if you want to keep this issue open or document it.

**Comment by ryanheise** [comment]
The troubleshooting section hasn't been added yet, so I'll leave it open.

**Comment by ryanheise** [comment]
I've added a troubleshooting section to the README explaining server headers, hence I'll close this issue.
