### ISSUE TITLE
just_audio_background plans to support multiple players

### ISSUE THREAD

**Issue by davefaliskie** [ryanheise/just_audio#925]
**Is your feature request related to a problem? Please describe.**
Yes, as mentioned in the documentation this package works great when the app has only one `just_audio` player. However, if the app has multiple players this does not work.

**Describe the solution you'd like**
Support multiple `just_audio` players. Allow for setting the "current" player which would then pass that player's audio to the background.

**Describe alternatives you've considered**
The current alternative is to use `audio_service`, definitely seems possible to get background audio working for multiple players, likely with a `SwitchAudioHandler`, so far I've been unsuccessful.

**Additional context**
I've tried using `audio_service` but I have my `just_audio` player defined in an existing custom class with several custom functions that rely on accessing the player. A few issues I've not been able to figure out yet are:
- how to still access the `just_audio` player from the custom class if it's defined in a `BaseAudioHandler`
- or how to define the player outside the `BaseAudioHandler` and still use it within the handler
- How to actually use `SwitchAudioHandler` to change between two different AudioHandlers 

I'll keep looking into `audio_service` but was curious if supporting multiple players was planned for this package. Thanks for all the great & helpful audio resources!

**Comment by ryanheise** [comment]
Multiple background players is not planned. There are many different ways to go about building an app with multiple players which means that it would be complex to hard code anything into this plugin. However, audio service makes all of these complex scenarios possible. If you have more complex requirements, it is best to use audio service from the start so that you don't later run into limitations.
