### ISSUE TITLE
Save audio with modified pitch.

### ISSUE THREAD

**Issue by KSS-10** [ryanheise/just_audio#931]
**Is your feature request related to a problem? Please describe.**
We want to save the audio with desired pitch into the device but the setPitch() function doesn't return any audio-contents.

**Describe the solution you'd like**
We just wanted the audio-contents after setting the speed and pitch returned through there respective function, so that it's easy to save the file into the device with the modified speed or pitch.

Future<void> setPitch(final double pitch) async {
    if (_disposed) return;
    _playbackEvent = _playbackEvent.copyWith(
      updatePosition: position,
      updateTime: DateTime.now(),
    );
    _playbackEventSubject.add(_playbackEvent);
    _pitchSubject.add(pitch);
    await (await _platform).setPitch(SetPitchRequest(pitch: pitch));
  }

above function doesn't return anything to save the audio-content for the desired pitch.

**Comment by ryanheise** [comment]
That's because just_audio is "just" an audio player. If you want to produce new audio files, you'll need to search for a different plugin that does that.

**Comment by KSS-10** [comment]
Ohh, but its good if that feature will also be added in just_audio, it'll allow us to save the modified pitch audio content to the device.

**Comment by ryanheise** [comment]
I have explained the justification for this in the README. It is better to have many plugins each performing a specific job and doing that job well. An app can then import exactly the set of plugins it actually needs. Rather than have one audio plugin that does everything, you get to import an audio player package, a Text-To-Speech package, an audio recorder plugin, etc. and so on if you want each of those. Or if your app doesn't need a recorder, you simply don't import that plugin.

Now the problem is that if a single plugin performed every conceivable audio function, you would be forced to include a lot of code that you're not actually using and this may cause problems. E.g. The presence of the recorder code means that your app will now need to declare that it needs record permissions, even though your app is not using them. Or, suppose you do want to use a recorder, but you want to be able to choose the best recorder plugin on its own merits. The vendor who makes the best audio player may not be the same as the vendor who makes the best recorder, so you'd like to be able to choose your favourite player and choose your favourite recorder.

I support the idea of single-responsibility plugins, and discourage monolithic plugins. Hence why you'll need to search for a different plugin for that particular responsibility (of editing, encoding and writing audio files). It is not what I'm building here in this project.
