### ISSUE TITLE
 just_audio_background supports only a single player instance flutter

### ISSUE THREAD

**Issue by Zeeshan-H** [ryanheise/just_audio#937]
**Which API doesn't behave as documented, and how does it misbehave?**
setAudioSource() method in the initState() method doesn't work if I donot dispose the player instance because the background music doesn't play if I navigate to the previous screen or any other screen.

**Minimal reproduction project**
Provide a link here using one of two options:
1. I used the code from here https://pub.dev/packages/just_audio_background/example
2. If the unmodified official example already reproduces the bug, just write "https://pub.dev/packages/just_audio_background/example".

**To Reproduce (i.e. user steps, not code)**
1. Go to 'Audo Player.'
2. Click on 'Play button'
3. Scroll down to 'Or press back button or move to any other screen the audio player stops and if remove dispose method it works but now it gives error about only single instance is supported.'

**Error messages**

```
Unhandled Exception: PlatformException(error, just_audio_background supports only a single player instance, null, null)
```

**Expected behavior**
I was expecting it to play another audio and override the existing audio but it kept playing the same audio even the setAudioSource() funcition is called in the initState() method.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Smartphone (please complete the following information):**
 - Device: [Samsung A52 S 5G]
 - OS: [13]

**Flutter SDK version**
3.7.3 
insert output of "flutter doctor" here
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19044.1526], locale en-PK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (not installed)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 2 categories.

**Additional context**
Please help me with this as I really liked the package but just resolve this issue. As i want to use the app also while playing the audio in the background.

**Comment by ryanheise** [comment]
@Zeeshan-H , you haven't provided a valid bug report. You say you haven't created a minimal reproduction project "yet", but that is necessary. Also, in the first section, you didn't actually cross reference this to the documentation.

(Also please note that my experience with you so far has involved a lot of back and forth trying to get you to follow the rules and procedures for this repo. I don't want to have to keep asking you to follow the instructions, so it would help you you just wait until you have read and followed the instructions. When everything is ready, then let me know.)

**Comment by Zeeshan-H** [comment]
Hi Ryanheise/Just_audio,

I already given you the link and tried my best follow the template. I
really need you to help me with this. The package is really good but the
error message is annoying.

If you could have a zoom meeting with me tht would be great.

Thanks,
Zeeshan Haidar

**Comment by Zeeshan-H** [comment]
I have created the minimal reproduction project as well using the same code from here: 
https://pub.dev/packages/just_audio_background/example

**Comment by ryanheise** [comment]
Your bug report still says you haven't done it "yet".

And you still haven't edited your bug report to fix the first section as requested.

Can I just check, do you actually know that there is a bug? Because it seems like you're not actually sure how to use the plugin. GitHub issues is not the place to ask for help using the plugin, it is the place to report legitimate issues where you can establish in section 1 that it is indeed a bug, and provide in section 2 the minimal reproduction project. If it's not a bug in just_audio_background and you just want to ask a question, then StackOverflow is the place to do that.

**Comment by Zeeshan-H** [comment]
Yes, I did on stack overflow but no one replied. There is a bug for sure in
your package because its not all about knowing how to use the package
however could be.

**Comment by ryanheise** [comment]
> Yes, I did on stack overflow but no one replied.

Can you provide a link to the StackOverflow page where you asked this question? I did find one question by you but it was a different question about audio_service, and it actually wasn't even technically a question, so nobody could answer it. I replied pretty quickly in a comment asking you to clarify it to make it into a question, which you never did. If there is another question that was specifically about this just_audio_background issue, where is it?

> There is a bug for sure in your package because its not all about knowing how to use the package however could be.

Well you still haven't submitted a valid bug report. There is no way that the unmodified official example exhibits the bug you claim simply because you talk about removing a line of code -- so it literally can't be "unmodified". So I think you're really experiencing the issue on a different project, but you just don't want to take the time to create a proper minimal reproduction project.

**Comment by Zeeshan-H** [comment]
No even in the example link i sent you has the same issue. If i add a button and navigate to another page or simply pop back to previous screen the backgroud audio doesnt work.Therefore i tried to get rid of disposing the audio player instance.

**Comment by ryanheise** [comment]
How can that be the "unmodified" example if you are modifying it by adding more pages and buttons? That's exactly what I've been trying to tell you. The unmodified example is not a valid reproduction project for your bug report. What you need is a modified project.

**Comment by ryanheise** [comment]
I'm sorry, I have wasted a lot of my time trying to get you to submit a valid bug report or submit a valid question to StackOverflow, and you keep refusing to do so. Due to my health condition, this is not the way I want to spend my limited time in front of a computer.

And your latest comment on StackOverflow was quite insulting to my intelligence, claiming that the reason I'm not answering you is because I don't know the answer, when I already told you the reason I'm not answering you is because you have not yet submitted a valid bug report. Despite my prolonged efforts, you have used up (and far exceeded) my time budget. Given my health condition, I don't appreciate your disrespecting the amount of time it takes me to deal with these issues, and if you don't want to take the time to fully understand the instructions to submit a bug report, then please don't submit one in the first place.

I will close and lock this issue since you have shown above and in the previous issue which you hijacked that you are not interested in paying attention to the fine details of what I have been asking you to do.
