### ISSUE TITLE
Add option to customize buffering behaviour

### ISSUE THREAD

**Issue by paul-blum** [ryanheise/just_audio#938]
**Is your feature request related to a problem? Please describe.**
The AudioPlaoyer always buffers the entire song. I would like to custoize this behavior and only buffer up to say 6 seconds. It appears that the AndroidLoadControl paramaters like maxBufferDuration have no effect on the buffering startegy. It buffers the entire song no matter what I set the maxBufferDuration to. Also the other parameters like targetBufferBytes, prioritizeTimeOverSizeThresholds have no effect.

**Describe the solution you'd like**
If I set the maxBufferDuration to say Duration(seconds: 6), it should olny buffer six seconds of the song and not the entire song.

**Describe alternatives you've considered**
I don't think there are any alternatives, the parameters should just have the desired effect.

**Comment by ryanheise** [comment]
> I don't think there are any alternatives, the parameters should just have the desired effect.

The way you worded that sounds like you should have submitted a bug report rather than a feature request.

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/DefaultLoadControl.html

Through the process of submitting a bug report, you'll be able to narrow it down to either this API, or maybe down to some other layer.

**Comment by paul-blum** [comment]
Thank you for your reply. Can you hint me into the direction as to how to make buffering work? I.e. don't buffer the entire don't but only up to a certain limit ahead?

**Comment by ryanheise** [comment]
This site is used for submitting issues, and it seemed like you found a bug. I can't investigate that unless you submit a bug report.

In any case I will close this issue since it does not make sense to make a feature request of a feature that already exists which may be a bug report disguised. When you click new issue, there is an option for submitting a bug report. If you don't think it's a bug anymore, there is another option there for asking for community support.
