### ISSUE TITLE
There is no way to find current song is completed. 

### ISSUE THREAD

**Issue by rameshkec85** [ryanheise/just_audio#943]
I have spend lot of time to go through the documentation. But I couldn't find a way to listen to song is completed. So that i couldn't track how long song is being listened . I want to perform some analytics in my project based on how many hours songs are being listened etc.. Exo Player we had a analytics listener.  Any suggestions would be appreciated ?

**Comment by rameshkec85** [comment]
@ryanheise Any help ?

**Comment by ryanheise** [comment]
This is not the place to ask for help. When you click on new issue, please read the options carefully as it explains how to use these resources correctly.

**Comment by rameshkec85** [comment]
@ryanheise I understand that.... But Functionality is missing in this library. Thats why I am pointing into this forum. Please check it once again if i am wrong. ITS BUG THEN

**Comment by ryanheise** [comment]
@rameshkec85 You only said that you tried to find it in the documentation and failed to do so. Look, you have two choices:

1. If you're sure this feature is definitely missing, then you should not submit a BUG report. Again, I told you to read the options carefully because one of the options is for a new feature request. And even if you thought this was a bug report, you again ignored the instructions for submitting a bug report which is why you got the bot message. You're just ignoring everything.
2. The other option is that if you are NOT SURE if the feature is missing, then you are simply asking for help on how to achieve your use case. And that is asking for help. Please, do not post that here, this place is only for people who have done the research and want to contribute to the project. Making me have to explain to you that you're ignoring all of the instructions is not a positive contribution, it's actually taking my time away from doing real work on the project.
