### ISSUE TITLE
How to disable playback in AVQueuePlayer of just_audio

### ISSUE THREAD

**Issue by jackwill99** [ryanheise/just_audio#949]
I'm trying to add airPlay in my project and it works. But in audio sharing airPlay has playback control. So, when I play airPlay, audio is playing like a video with plackback controller. I can control this in AVPlayer swift like `player?.allowsExternalPlayback = false;`. But you are using AVQueuePlayer and Objective C. How can I solve this or you can update airplay features in just_audio package. 

[Here](https://docs.jwplayer.com/players/docs/ios-add-an-airplay-button-to-an-app-v3) is the sample of airPlay button and it works.

**Comment by ryanheise** [comment]
Can you please submit this as a valid issue that conforms to the template? I will then be able to investigate.

**Comment by jackwill99** [comment]
@ryanheise bot closed issue. What is the valid template? Please ...

**Comment by ryanheise** [comment]
When you click on new issue, you are presented with the different types of bug templates. You clicked the "Bug" template.

After clicking the Bug template, the next screen contains an edit text box which is pre-filled in with the template.

The very first line in that editable text box says:

```
<!--    ALL SECTIONS BELOW MUST BE COMPLETED   -->
```

Unfortunately, it seems you ignored this and deleted it all rather than filling in all of the sections are instructed.

Am I wrong? When you click it, did you not see the "ALL SECTIONS BELOW MUST BE COMPLETED" text? Or am I right and you just ignored it and deleted it?

By the way, please don't spam multiple issues. It makes it difficult for people to search through past issues if there are multiple duplicates.
